update  currentstock 
set cwhcode=cwhcode   
where cwhcode=N'14' and cinvcode=N'601_000079' and isnull(cfree1,'')=N'' and isnull(cfree2,'')=N'' and isnull(cfree3,'')=N'' and isnull(cfree4,'')=N'' and isnull(cfree5,'')=N'' and isnull(cfree6,'')=N'' and isnull(cfree7,'')=N'' and isnull(cfree8,'')=N'' and isnull(cfree9,'')=N'' and isnull(cfree10,'')=N'' and isnull(cbatch,'')=N'' and isnull(isotype,0)=0 and isnull(isodid,'')=N'' and  (( isnull(iquantity,0)-isnull(fstopquantity ,0)) < 753 or (isnull(inum,0)-isnull(fstopnum,0))<0)



insert into rdrecord08(id,brdflag,cvouchtype,cbustype,csource,cwhcode,ddate,ccode,cmaker,vt_id,iswfcontrolled,dnmaketime,dnmodifytime,dnverifytime) values (N'1000012207',N'1',N'08',N'预留入库',N'3',N'14',N'2015-11-19',N'1000012207',N'Jason',67,0, getdate(), Null , Null )

 Insert Into rdrecord08_ExtraDefine(id,chdefine3,chdefine11,chdefine13,chdefine16) Values (1000012207,NULL,NULL,NULL,NULL)
 
 
 insert into #LPWriteBackTbl (cinvcode,isotype,isodid,iquantity,inum,cfree1,cfree2,cfree3,cfree4,cfree5,cfree6,cfree7,cfree8,cfree9,cfree10) values ( N'601_000079',5,N'J0004/16',500,0,N'',N'',N'',N'',N'',N'',N'',N'',N'',N'')
 
 
set nocount on 
Insert Into rdrecords08(autoid,id,cinvcode,inum,iquantity,iunitcost,iprice,ipunitcost,ipprice,cbatch,cvouchcode,cinvouchcode,cinvouchtype,isoutquantity,isoutnum,cfree1,cfree2,dvdate,itrids,cposition,cdefine22,cdefine23,cdefine24,cdefine25,cdefine26,cdefine27,citem_class,citemcode,cname,citemcname,cfree3,cfree4,cfree5,cfree6,cfree7,cfree8,cfree9,cfree10,cbarcode,inquantity,innum,cassunit,dmadedate,imassdate,cdefine28,cdefine29,cdefine30,cdefine31,cdefine32,cdefine33,cdefine34,cdefine35,cdefine36,cdefine37,icheckids,cbvencode,ccheckcode,icheckidbaks,crejectcode,irejectids,ccheckpersoncode,dcheckdate,cmassunit,irsrowno,ioritrackid,coritracktype,cbaccounter,dbkeepdate,bcosting,bvmiused,ivmisettlequantity,ivmisettlenum,cvmivencode,iinvsncount,cserviceoid,cbserviceoid,iinvexchrate,corufts,iexpiratdatecalcu,cexpirationdate,dexpirationdate,cciqbookcode,ibondedsumqty,isodid,isotype,csocode,isoseq,cbatchproperty1,cbatchproperty2,cbatchproperty3,cbatchproperty4,cbatchproperty5,cbatchproperty6,cbatchproperty7,cbatchproperty8,cbatchproperty9,cbatchproperty10,cbmemo,irowno,strowguid,cbsourcecodels,igroupno,idebitids,idebitchildids,cbsysbarcode,icrmvouchids,ccrmvouchcode,iposflag)
	 Values (1000044281,1000012207,N'601_000079',Null,500,Null,Null,Null,Null,Null,Null,Null,Null,0,0,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,500,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,1,Null,Null,Null,Null,0,0,Null,Null,Null,Null,Null,Null,Null,Null, Null ,Null,Null,Null,Null,N'J0004/16',5,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,1,Null,Null,Null,Null,Null,Null,Null,Null,Null) Insert Into rdrecords08_ExtraDefine(autoid,cbdefine3,cbdefine4,cbdefine1,cbdefine9,cbdefine15) Values (1000044281,NULL,NULL,NULL,NULL,NULL)
Insert Into rdrecords08(autoid,id,cinvcode,inum,iquantity,iunitcost,iprice,ipunitcost,ipprice,cbatch,cvouchcode,cinvouchcode,cinvouchtype,isoutquantity,isoutnum,cfree1,cfree2,dvdate,itrids,cposition,cdefine22,cdefine23,cdefine24,cdefine25,cdefine26,cdefine27,citem_class,citemcode,cname,citemcname,cfree3,cfree4,cfree5,cfree6,cfree7,cfree8,cfree9,cfree10,cbarcode,inquantity,innum,cassunit,dmadedate,imassdate,cdefine28,cdefine29,cdefine30,cdefine31,cdefine32,cdefine33,cdefine34,cdefine35,cdefine36,cdefine37,icheckids,cbvencode,ccheckcode,icheckidbaks,crejectcode,irejectids,ccheckpersoncode,dcheckdate,cmassunit,irsrowno,ioritrackid,coritracktype,cbaccounter,dbkeepdate,bcosting,bvmiused,ivmisettlequantity,ivmisettlenum,cvmivencode,iinvsncount,cserviceoid,cbserviceoid,iinvexchrate,corufts,iexpiratdatecalcu,cexpirationdate,dexpirationdate,cciqbookcode,ibondedsumqty,isodid,isotype,csocode,isoseq,cbatchproperty1,cbatchproperty2,cbatchproperty3,cbatchproperty4,cbatchproperty5,cbatchproperty6,cbatchproperty7,cbatchproperty8,cbatchproperty9,cbatchproperty10,cbmemo,irowno,strowguid,cbsourcecodels,igroupno,idebitids,idebitchildids,cbsysbarcode,icrmvouchids,ccrmvouchcode,iposflag)
	 Values (1000044282,1000012207,N'601_000079',Null,-500,Null,Null,Null,Null,Null,Null,Null,Null,0,0,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,-500,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,2,Null,Null,Null,Null,0,0,Null,Null,Null,Null,Null,Null,Null,Null, Null ,Null,Null,Null,Null,Null,0,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,2,Null,Null,Null,Null,Null,Null,Null,Null,Null) Insert Into rdrecords08_ExtraDefine(autoid,cbdefine3,cbdefine4,cbdefine1,cbdefine9,cbdefine15) Values (1000044282,NULL,NULL,NULL,NULL,NULL)

 set nocount off 
 
 